### PR TITLE
Add reservation api

### LINKED ISSUE #30: Integrate API endpoint to add reservation form

### PR DESCRIPTION
**Pull request by DavidEspinoG**
Hi @NicolasAndrehh, 
In this PR I included an API call to save a reservation when the user submit the create reservation form

### CODE REVIEW

**Review by NicolasAndrehh — COMMENTED** [review]
# STATUS APPROVED ✅
Great job @DavidEspinoG, feel free to merge it! 😄🎊

**Review by NicolasAndrehh — APPROVED** [review]

**Comment by NicolasAndrehh** [comment]
# IMPORTANT ⚠️
Hey @DavidEspinoG, I just realize that you didn't add an `useEffect` in your component in order to fetch videogames (If you reload the page in reserve page the redux store will be empty and you'll need to fetch all videogames again) in order to solve it you could use an if to fetch only if videogames.all is empty

Also in the Reserve component it would be good if you change the name of the variable `mockData` to `videogames`

Please address this issues before mergin 🙏.

**Comment by DavidEspinoG** [comment]
Hello, @NicolasAndrehh. Thanks a lot for letting me know, I will take a look to that immediately.

**Comment by DavidEspinoG** [comment]
Hello @NicolasAndrehh I just fixed the issue you commented, thanks a lot!

**Pull request merged**
